[package]
description = "Resumable state machine based Postgres tasks"
edition = "2021"
license = "MIT"
name = "pg_task"
repository = "https://github.com/imbolc/pg_task"
version = "0.2.2"

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["std", "serde"] }
code-path = "0.4"
displaydoc = "0.2"
num_cpus = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
source-chain = "0.1"
sqlx = { version = "0.8", features = [
  "json",
  "chrono",
  "postgres",
  "runtime-tokio-rustls",
  "uuid",
] }
thiserror = "2"
tokio = "1"
tracing = "0.1"

[dev-dependencies]
anyhow = "1"
dotenv = "0.15"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
